/*
 * This source file was generated by the Gradle 'init' task
 */
package projet.poo;

import java.io.IOException;
import java.util.Map;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        GestionnaireFrequences g = new CompteurFrequences("corpus");
        g.calculerFrequences();
        EcrireCSV e = new FrequenceToCSV(g.getUngramme(), g.getBigramme(), g.getTrigramme(), g.getTailleTotal());
        System.out.println(g.getUngramme());
        try {
            e.ecrisDansCSV();
        } catch (IOException e1) {
            // TODO Auto-generated catch block
            e1.printStackTrace();
        }

        Map<String, String> dispositionClavier = Map.of(
    "A", "shift,a",  // Pour écrire "A", il faut appuyer sur Shift et "a"
    "a", "a",        // Pour écrire "a", une seule touche est nécessaire
    ",", "comma"     // Pour écrire ",", une touche "comma" suffit
);
        // Lecture et traitement du fichier CSV
        String cheminFichier = "frequence1.csv"; // Chemin du fichier CSV généré
        System.out.println("Lecture et tri du fichier CSV :");
        LectureEtTraitementCSV.traiterCSV(cheminFichier,dispositionClavier);
    }
}
